import type { Metadata } from "next";
import "@workspace/ui/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex justify-center align-center">
        <div className="w-full max-w-[640px] p-[24px] bg-(--background)">
          {children}
        </div>
      </body>
    </html>
  );
}
